# manipular cadeia de textos
frase = 'Curso em Vídeo Python'
print(frase[3])
print(frase[3:10])
print(frase[::2])
print(len(frase))
print(frase.count('o'))
print(frase.count('o', 0, 13))
print(frase.find('deo'))
print('Curso' in frase)
print(frase.replace('Python', 'Android'))
print(frase.upper())
print(frase.lower())
print(frase.capitalize())
print(frase.title())
frase2 = '   Aprenda Python  '
print(frase2)
print(frase2.strip())
print(frase2.rstrip())
print(frase2.lstrip())
dividido = frase.split()
print(dividido)
print(dividido[2])
print(dividido[2][3])
print('-'.join(dividido))
