n = input('Digite algo:')
print('Decimal:', (n.isdecimal()))
print('Letra alfabética:', (n.isalpha()))
print('Alphanumérico:', (n.isalnum()))
print('Digitos:', (n.isdigit()))
print('Numérico:', (n.isnumeric()))
print('Minúsculo:', (n.islower()))
print('Maiúsculo:'), (n.isupper())
print('Capitalizada:')(n.istitle())
